
package panels;

import DataBase.Database;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import fitnesscampsystem.userLogs;
import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import net.proteanit.sql.DbUtils;


public class MRex extends javax.swing.JPanel {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public MRex() {
        
        initComponents();
        con = Database.ConnectDB();
        Table_view();
        ExpiredSubs.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        ExpiredSubs.getTableHeader().setOpaque(false);
        ExpiredSubs.getTableHeader().setBackground(new Color(48, 173, 95));
        ExpiredSubs.getTableHeader().setForeground(new Color(255, 255, 255));
        ExpiredSubs.setRowHeight(25);
        ExpiredSubs.getTableHeader().setReorderingAllowed(false);
    }
    
    
     public void Table_view() {
        try {
//             select * from table where strftime('%m', created_date) == strftime('%m','now')
            String sql = "SELECT members_id, mfirstName, mlastName from Members_Tbl WHERE  strftime('%m', End) == strftime('%m', 'now')";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            ExpiredSubs.setModel(DbUtils.resultSetToTableModel(rs));

            pst.close();
            rs.close();
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ExpiredSubs = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        ExpiredSubs = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        ExpiredSubs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Last Name", "Start", " End"
            }
        ));
        ExpiredSubs.setSelectionBackground(new java.awt.Color(51, 210, 102));
        jScrollPane1.setViewportView(ExpiredSubs);

        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String path = "";
        
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x= j.showSaveDialog(this);
        
        
        if (x== JFileChooser.APPROVE_OPTION){
            path = j.getSelectedFile().getPath();
        }
        Document doc = new Document();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"MonthIncome.pdf"));
            
            doc.open();
            PdfPTable tbl = new PdfPTable(5);
            
            
            tbl.addCell("FIRSTNAME");
            tbl.addCell("LASTNAME");
            tbl.addCell("GENDER");
            tbl.addCell("START");
            tbl.addCell("END");
            
            
            
            for (int i = 0; i < ExpiredSubs.getRowCount(); i++) {
                String fname = ExpiredSubs.getValueAt(i, 0).toString();
                String lname = ExpiredSubs.getValueAt(i, 1).toString();
                String gender = ExpiredSubs.getValueAt(i, 2).toString();
                String start = ExpiredSubs.getValueAt(i, 3).toString();
                String end = ExpiredSubs.getValueAt(i, 4).toString();
                
                
                tbl.addCell(fname);
                tbl.addCell(lname);
                tbl.addCell(gender);
                tbl.addCell(start);
                tbl.addCell(end);
                
            }
            
            doc.add(tbl);
           
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(userLogs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(userLogs.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        doc.close();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ExpiredSubs;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
